# Generated by Django 4.2.20 on 2025-09-27 12:22

from django.db import migrations, models
import reconhecimento_facial.models


class Migration(migrations.Migration):

    dependencies = [
        ('reconhecimento_facial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedphotos',
            name='image',
            field=models.ImageField(upload_to=reconhecimento_facial.models.user_directory_path),
        ),
    ]
